import os
import google.generativeai as genai
# Configure API key safely
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)
def enhance_text_to_ai_persona(draft_text):
    if not api_key:
        return "⚠️ Error: GEMINI_API_KEY is not set in Render Environment Variables."
    
    try:
        # Using a "lite" model ensures you don't hit the free-tier quota limits
        target_model = 'gemini-flash-lite-latest'
        model = genai.GenerativeModel(target_model)
        
        prompt = f"""
You are an advanced, highly professional, and helpful AI assistant for a Telegram group.
The admin has written a quick draft answer to a user's question. 
Your job is to rewrite this draft into a polished, professional response that sounds like it was generated by an authentic, highly capable AI assistant.
CRITICAL RULES:
1. DO NOT use ANY emojis under any circumstances. Keep it text-only.
2. Maintain the exact meaning and information of the admin's draft.
3. Be polite, clear, and professional.
4. Output ONLY the rewritten text, with no introductory or concluding conversational filler.
Admin's Draft:
{draft_text}
"""
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        try:
            available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
            models_str = ", ".join(available_models)
        except Exception:
            models_str = "Could not fetch list."
            
        return f"⚠️ Error: {e}\n\nAvailable models for your API key: {models_str}"